title: Full Name
logo: /images/headshot_circle.png
#description: text below image
#show_downloads: true
#theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme