title: Divij Kulshrestha
logo: /images/headshot_circle_small.png
description:
  <br><br>
  <a href="https://www.linkedin.com/in/divij-kulshrestha/">View My LinkedIn Profile</a>
  <br><br> 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme