#divij_gh_pages
title: FirstName LastName
logo: /images/headshot_circle.png
description: 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme